services:
    TweedeGolf\PrometheusClient\Storage\ApcuAdapter:
      class: TweedeGolf\PrometheusClient\Storage\ApcuAdapter
    TweedeGolf\PrometheusClient\Storage\ApcAdapter:
      class: TweedeGolf\PrometheusClient\Storage\ApcAdapter